import {
SwimmingIcon,
  WaveIcon,
  Dumbbell01Icon,
  Car01Icon,
  Shield01Icon,
  CustomerSupportIcon,
  UserCheck01Icon,
  Sun01Icon,
  ViewIcon,
  Wardrobe01Icon,
  KitchenUtensilsIcon,
  Tree01Icon,
  ShoppingBag01Icon,
  Restaurant01Icon,
  FireIcon,
  Train01Icon,
  Tv01Icon,
  BookOpen01Icon,
  Settings01Icon,
  CheckListIcon,
  BedDoubleIcon,
  Bathtub01Icon,
  House01Icon,
  Building01Icon,
  RulerIcon,
  UserIcon,
  Menu01Icon,
  Search01Icon,
  FilterHorizontalIcon,
  ArrowRight01Icon,
  ArrowLeft01Icon,
  Download01Icon,
  Share01Icon,
  FavouriteIcon,
  CallIcon,
  SentIcon,
  WhatsappIcon,
  TelegramIcon,
  InstagramIcon,
  Facebook01Icon,
  Linkedin01Icon,
  YoutubeIcon,
  Globe02Icon,
  Location01Icon,
  Mail01Icon,
  Calendar01Icon,
  Money01Icon,
  CreditCardIcon,
  File01Icon,
  Image01Icon,
  Video01Icon,
  Camera01Icon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  VolumeHighIcon,
  VolumeOffIcon,
  Settings02Icon,
  Logout01Icon,
  Login01Icon,
  UserAdd01Icon,
  UserRemove01Icon,
  UserGroupIcon,
  Layout01Icon,
  Layout02Icon,
  Layout03Icon,
  GridIcon,
  ListViewIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  CheckmarkCircle01Icon,
  AlertCircleIcon,
  InformationCircleIcon,
  HelpCircleIcon,
  Delete01Icon,
  Edit01Icon,
  Add01Icon,
  Remove01Icon,
  Cancel01Icon,
  Tick01Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  Home01Icon,
  DashboardSquare01Icon,
  Comment01Icon,
  Tag01Icon,
  Layers01Icon,
  Briefcase01Icon,
  PencilEdit01Icon,
  Delete02Icon,
  Upload01Icon,
  Download02Icon,
  Link01Icon,
  Unlink01Icon,
  Copy01Icon,
  ClipboardIcon,
  Scissor01Icon,
  FloppyDiskIcon,
  PrinterIcon,
  Share05Icon,
  FilterIcon,
  SortByUp01Icon,
  SortByDown01Icon,
  Search02Icon,
  RefreshIcon,
  ReloadIcon,
  Time01Icon,
  Calendar02Icon,
  Clock01Icon,
  AlarmClockIcon,
  Timer01Icon,
  HourglassIcon,
  CalculateIcon,
  Calculator01Icon,
  ChartBarLineIcon,
  PieChartIcon,
  ChartLineData01Icon,
  ChartHistogramIcon,
  ArrowExpand01Icon,
  SnowIcon,
  Backward01Icon,
  Forward01Icon,
  ArrowShrink01Icon,
  ZoomInAreaIcon,
  ZoomOutAreaIcon
} from "@hugeicons/core-free-icons";

// 1. Base Icons Map (from imports)
const BASE_ICONS: Record<string, any> = {
  SwimmingIcon,
  WaveIcon,
  Dumbbell01Icon,
  Car01Icon,
  Shield01Icon,
  CustomerSupportIcon,
  UserCheck01Icon,
  Sun01Icon,
  ViewIcon,
  Wardrobe01Icon,
  KitchenUtensilsIcon,
  Tree01Icon,
  ShoppingBag01Icon,
  Restaurant01Icon,
  FireIcon,
  Train01Icon,
  Tv01Icon,
  BookOpen01Icon,
  Settings01Icon,
  CheckListIcon,
  BedDoubleIcon,
  Bathtub01Icon,
  House01Icon,
  Building01Icon,
  RulerIcon,
  UserIcon,
  Menu01Icon,
  Search01Icon,
  FilterHorizontalIcon,
  ArrowRight01Icon,
  ArrowLeft01Icon,
  Download01Icon,
  Share01Icon,
  FavouriteIcon,
  CallIcon,
  SentIcon,
  WhatsappIcon,
  TelegramIcon,
  InstagramIcon,
  Facebook01Icon,
  Linkedin01Icon,
  YoutubeIcon,
  Globe02Icon,
  Location01Icon,
  Mail01Icon,
  Calendar01Icon,
  Money01Icon,
  CreditCardIcon,
  File01Icon,
  Image01Icon,
  Video01Icon,
  Camera01Icon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  VolumeHighIcon,
  VolumeOffIcon,
  Settings02Icon,
  Logout01Icon,
  Login01Icon,
  UserAdd01Icon,
  UserRemove01Icon,
  UserGroupIcon,
  Layout01Icon,
  Layout02Icon,
  Layout03Icon,
  GridIcon,
  ListViewIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  CheckmarkCircle01Icon,
  AlertCircleIcon,
  InformationCircleIcon,
  HelpCircleIcon,
  Delete01Icon,
  Edit01Icon,
  Add01Icon,
  Remove01Icon,
  Cancel01Icon,
  Tick01Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  Home01Icon,
  DashboardSquare01Icon,
  Comment01Icon,
  Tag01Icon,
  Layers01Icon,
  Briefcase01Icon,
  PencilEdit01Icon,
  Delete02Icon,
  Upload01Icon,
  Download02Icon,
  Link01Icon,
  Unlink01Icon,
  Copy01Icon,
  ClipboardIcon,
  Scissor01Icon,
  FloppyDiskIcon,
  PrinterIcon,
  Share05Icon,
  FilterIcon,
  SortByUp01Icon,
  SortByDown01Icon,
  Search02Icon,
  RefreshIcon,
  ReloadIcon,
  Time01Icon,
  Calendar02Icon,
  Clock01Icon,
  AlarmClockIcon,
  Timer01Icon,
  HourglassIcon,
  CalculateIcon,
  Calculator01Icon,
  ChartBarLineIcon,
  PieChartIcon,
  ChartLineData01Icon,
  ChartHistogramIcon,
  ArrowExpand01Icon,
  SnowIcon,
  Backward01Icon,
  Forward01Icon,
  ArrowShrink01Icon,
  ZoomInAreaIcon,
  ZoomOutAreaIcon,
};

// 2. Aliases
const ALIASES: Record<string, any> = {
  AirConditioner01Icon: SnowIcon,
  Calculate01Icon: CalculateIcon,
  ChartPieIcon: PieChartIcon,
  ChevronDownIcon: ArrowDown01Icon,
  ChevronLeftIcon: ArrowLeft01Icon,
  ChevronRightIcon: ArrowRight01Icon,
  ChevronUpIcon: ArrowUp01Icon,
  Cut01Icon: Scissor01Icon,
  CutIcon: Scissor01Icon,
  Globe01Icon: Globe02Icon,
  HistoryIcon: Clock01Icon,
  PasteIcon: ClipboardIcon,
  PrintIcon: PrinterIcon,
  Save01Icon: FloppyDiskIcon,
  ShrinkIcon: ArrowShrink01Icon,
  Stopwatch01Icon: Timer01Icon,
  SyncIcon: ReloadIcon,
  TrashCan01Icon: Delete02Icon,
  Wave01Icon: WaveIcon,
  CheckmarkIcon: Tick01Icon,
};

// 3. Combined Map (Exported for Picker)
export const ALL_ICONS: Record<string, any> = {
  ...BASE_ICONS,
  ...ALIASES,
};

export const LUCIDE_TO_HUGEICONS: Record<string, any> = {
  // Water / Pool
  Waves: WaveIcon,
  Pool: SwimmingIcon,
  Droplets: WaveIcon,
  
  // Gym / Fitness
  Dumbbell: Dumbbell01Icon,
  Activity: ChartBarLineIcon,
  
  // Transport
  Car: Car01Icon,
  Parking: Car01Icon, // Fallback
  Bus: Train01Icon, // Approximate
  Train: Train01Icon,
  TrainFront: Train01Icon,
  
  // Security
  Shield: Shield01Icon,
  ShieldCheck: Shield01Icon,
  Lock: Shield01Icon,
  
  // Services
  ConciergeBell: CustomerSupportIcon,
  UserCheck: UserCheck01Icon,
  User: UserIcon,
  
  // Nature / Views
  Sun: Sun01Icon,
  Moon: Sun01Icon, // Fallback
  Trees: Tree01Icon,
  Tree: Tree01Icon,
  PalmTree: Tree01Icon,
  Mountain: ViewIcon,
  View: ViewIcon,
  MapPin: Location01Icon,
  Wind: SnowIcon, // Or Fan
  
  // Shopping / Food
  ShoppingBag: ShoppingBag01Icon,
  Store: ShoppingBag01Icon,
  Utensils: Restaurant01Icon,
  ChefHat: Restaurant01Icon, // Fallback
  Flame: FireIcon,
  Coffee: Restaurant01Icon,
  
  // Home
  Bed: BedDoubleIcon,
  Bath: Bathtub01Icon,
  Fan: SnowIcon,
  AirVent: SnowIcon,
  Warehouse: Wardrobe01Icon, // For "builtin_wardrobes" mapping
  Refrigerator: KitchenUtensilsIcon, // Fallback
  Tv: Tv01Icon,
  BookOpen: BookOpen01Icon,
  HardHat: Settings01Icon, // Maintenance
  Home: Home01Icon,
  Building: Building01Icon,
  Building2: Building01Icon,
  
  // Other
  PawPrint: UserIcon, // Fallback if Paw not imported, or use "Happy"
  CheckCircle2: CheckmarkCircle01Icon,
  FileText: File01Icon,
  Download: Download01Icon,
  Send: SentIcon,
  Phone: CallIcon,
  Move: ArrowExpand01Icon,
  Maximize: ArrowExpand01Icon,
  Maximize2: ArrowExpand01Icon,
  ChevronRight: ArrowRight01Icon,
  ChevronLeft: ArrowLeft01Icon,
  ChevronDown: ArrowDown01Icon,
  ChevronUp: ArrowUp01Icon,
  Search: Search01Icon,
  Menu: Menu01Icon,
  X: Cancel01Icon, // Replaces CloseIcon
  Plus: Add01Icon,
  Trash2: Delete02Icon,
  Edit: PencilEdit01Icon,
  Settings: Settings02Icon,
  LogOut: Logout01Icon,
  Filter: FilterIcon,
  ArrowUpDown: SortByUp01Icon, // Approx
  
  // Fallbacks for known missing
  Landmark: Location01Icon,
  Users: UserGroupIcon,
  Layers: Layers01Icon,
  LayoutDashboard: DashboardSquare01Icon,
  Briefcase: Briefcase01Icon,
  Tag: Tag01Icon,
  MessageSquare: Comment01Icon,
};

export const AMENITY_TO_HUGEICONS: Record<string, any> = {
  shared_pool: SwimmingIcon,
  private_pool: SwimmingIcon,
  kids_pool: SwimmingIcon,
  
  shared_gym: Dumbbell01Icon,
  private_gym: Dumbbell01Icon,
  gym: Dumbbell01Icon,
  
  covered_parking: Car01Icon,
  security: Shield01Icon,
  concierge: CustomerSupportIcon,
  
  balcony: ViewIcon, // Or Sun
  
  maid_service: UserCheck01Icon,
  maids_room: UserCheck01Icon,
  
  pets_allowed: UserIcon, // Use User or Paw if found
  
  beachfront: WaveIcon,
  public_parks: Tree01Icon,
  private_garden: Tree01Icon,
  
  near_mall: ShoppingBag01Icon,
  supermarket: ShoppingBag01Icon,
  
  restaurant: Restaurant01Icon,
  bbq_area: FireIcon,
  bbq_facility: FireIcon,
  
  near_transport: Train01Icon,
  
  central_ac: SnowIcon,
  
  builtin_wardrobes: Wardrobe01Icon,
  builtin_wardrobe: Wardrobe01Icon,
  
  equipped_kitchen: KitchenUtensilsIcon,
  builtin_appliances: KitchenUtensilsIcon,
  
  sea_view: WaveIcon,
  water_view: WaveIcon,
  landmark_view: Location01Icon,
  
  cable_tv: Tv01Icon,
  kids_playground: Tree01Icon, // Or Toy
  
  shared_spa: WaveIcon,
  private_jacuzzi: WaveIcon,
  
  study: BookOpen01Icon,
  
  maintenance: Settings01Icon,
};

export const getIconData = (name: string): any => {
  if (!name) return BASE_ICONS.CheckListIcon;
  
  // 1. Try direct match in LUCIDE_TO_HUGEICONS
  if (LUCIDE_TO_HUGEICONS[name]) return LUCIDE_TO_HUGEICONS[name];
  
  // 2. Try match in AMENITY_TO_HUGEICONS
  if (AMENITY_TO_HUGEICONS[name]) return AMENITY_TO_HUGEICONS[name];
  
  // 3. Try direct lookup in ALL_ICONS
  if (ALL_ICONS[name]) return ALL_ICONS[name];
  
  // 4. Fallback
  return BASE_ICONS.CheckListIcon;
};

export const DEFAULT_ICON = BASE_ICONS.CheckListIcon;

// Re-export all icons
export {
    Add01Icon,
    SnowIcon as AirConditioner01Icon, // Alias for backward compatibility if needed, but better to update usage
    AlarmClockIcon,
    AlertCircleIcon,
    ArrowDown01Icon,
    ArrowExpand01Icon,
    ArrowLeft01Icon,
    ArrowRight01Icon,
    ArrowUp01Icon,
    Backward01Icon,
    Bathtub01Icon,
    BedDoubleIcon,
    BookOpen01Icon,
    Briefcase01Icon,
    Building01Icon,
    CalculateIcon as Calculate01Icon, // Alias
    Calculator01Icon,
    Calendar01Icon,
    Calendar02Icon,
    CallIcon,
    Camera01Icon,
    Cancel01Icon,
    Car01Icon,
    ChartBarLineIcon,
    ChartHistogramIcon,
    ChartLineData01Icon,
    PieChartIcon as ChartPieIcon, // Alias
    CheckListIcon,
    CheckmarkCircle01Icon,
    CheckmarkIcon,
    ArrowDown01Icon as ChevronDownIcon, // Alias
    ArrowLeft01Icon as ChevronLeftIcon, // Alias
    ArrowRight01Icon as ChevronRightIcon, // Alias
    ArrowUp01Icon as ChevronUpIcon, // Alias
    Clock01Icon,
    Comment01Icon,
    Copy01Icon,
    CreditCardIcon,
    CustomerSupportIcon,
    Scissor01Icon as Cut01Icon, // Alias
    Scissor01Icon as CutIcon, // Alias
    DashboardSquare01Icon,
    Delete01Icon,
    Download01Icon,
    Download02Icon,
    Dumbbell01Icon,
    Edit01Icon,
    Facebook01Icon,
    FavouriteIcon,
    File01Icon,
    FilterHorizontalIcon,
    FilterIcon,
    FireIcon,
    Forward01Icon,
    Globe02Icon as Globe01Icon, // Alias
    GridIcon,
    HelpCircleIcon,
  Clock01Icon as HistoryIcon,
  Home01Icon,
    HourglassIcon,
    House01Icon,
    Image01Icon,
    InformationCircleIcon,
    InstagramIcon,
    KitchenUtensilsIcon,
    Layers01Icon,
    Layout01Icon,
    Layout02Icon,
    Layout03Icon,
    Link01Icon,
    Linkedin01Icon,
    ListViewIcon,
    Location01Icon,
    Login01Icon,
    Logout01Icon,
    Mail01Icon,
    Menu01Icon,
    Money01Icon,
    MoreHorizontalIcon,
    MoreVerticalIcon,
    ClipboardIcon as PasteIcon, // Alias
    PauseIcon,
    PencilEdit01Icon,
    PlayIcon,
    PrinterIcon as PrintIcon, // Alias
    RefreshIcon,
    ReloadIcon,
    Remove01Icon,
    Restaurant01Icon,
    RulerIcon,
    FloppyDiskIcon as Save01Icon, // Alias
    Search01Icon,
    Search02Icon,
    SentIcon,
    Settings01Icon,
    Settings02Icon,
    Share01Icon,
    Share05Icon,
    Shield01Icon,
    ShoppingBag01Icon,
    ArrowShrink01Icon as ShrinkIcon, // Alias
    SortByDown01Icon,
    SortByUp01Icon,
    StopIcon,
    Timer01Icon as Stopwatch01Icon, // Alias
    Sun01Icon,
    SwimmingIcon,
    ReloadIcon as SyncIcon, // Alias
    Tag01Icon,
    TelegramIcon,
    Time01Icon,
    Timer01Icon,
    Train01Icon,
    Delete02Icon as TrashCan01Icon, // Alias
    Tree01Icon,
    Tv01Icon,
    Unlink01Icon,
    Upload01Icon,
    UserAdd01Icon,
    UserCheck01Icon,
    UserGroupIcon,
    UserIcon,
    UserRemove01Icon,
    Video01Icon,
    ViewIcon,
    VolumeHighIcon,
    VolumeOffIcon,
    Wardrobe01Icon,
    WaveIcon as Wave01Icon, // Alias
    WhatsappIcon,
    YoutubeIcon,
    ZoomInAreaIcon,
    ZoomOutAreaIcon
};